### ISSUE TITLE
Could UtahLSM simulate reginal water-energy Balence？

### ISSUE THREAD

**Issue by andrewsoong** [UtahEFD/UtahLSM#24]
Hello，
I am a PhD student and I am major in Land-atmospere interaction.
I just wonder that UtahLSM is a reginal LSM ?
Could you provide documants of this model,just like User guide?
Thank you !

**Comment by pardyjak** [comment]
Andrew,
  The model is designed for small scale land-atmosphere interactions (e.g. Large-eddy simulations), but could be used for larger scales. Note that the subsurface moisture and heat transfer is treated with a one-dimensional finite difference method, which may be more computational effort that you want for a regional scale model. We are still writing up the documentation for the model.  Here is a brief description: 
"The model is based on the work of Shinglton (2010), the UtahLSM explicitly solves for the vertical transport of heat and moisture in a 1D soil column by solving finite difference versions of the heat and Richards equations. The surface energy budget and mass budgets are linked to a 1D vertical soil model. Conservation of energy is applied at the infinitely thin interface between the atmosphere and the ground. This results in a surface energy balance (SEB) between the net radiation flux, sensible heat flux, latent heat flux, and the ground heat flux. Conservation of mass is applied at the surface, resulting in a surface mass balance (SMB) between precipitation, soil moisture flux, and surface evaporation. The surface moisture that enforces this balance is found using an iterative procedure. Moisture evolution is predicted by implicitly solving the mixed-form of the Richards’ moisture diffusion equation and the SEB and SMB are tied together by the assumption that all of the moisture evaporated requires the same amount of energy to be transformed into a gas. The UtahLSM has 3 different soil models (Genuchten, 1980; Campbell, 1974; Brooks and Corey, 1964) and 3 different soil property descriptions (Clapp and Hornberger 1978; Cosby et al. 1984; Rawls et al. 1982). The UtahLSM does not have a run-off model, hence rain is distributed over cells and it is assumed that all rain-water infiltrates or evaporates."

**Comment by pardyjak** [comment]
Also, here is the Shingleton thesis that the model is based on.
[ShingletonThesis_final.pdf](https://github.com/UtahEFD/UtahLSM/files/4570930/ShingletonThesis_final.pdf)

**Comment by andrewsoong** [comment]
Thank you so much! @pardyjak
